### PR TITLE
MaryamHassan

### PR DESCRIPTION
**Pull request by maryamhassan1**
Fixed Leave rating view song title showing up 
Fixed POSTS SHOWING up on feed, and default view showing up with new posts.

### CODE REVIEW

**Comment by anzaruoft** [comment]
Looks good to me. Let's wait for the others to review it as well. We aren't sure if updating the posts works with the JSON format yet.

**Review by anzaruoft — COMMENTED** [review]
Looks Good. Lets get it checked by the rest too.

**Review by BennyKonishi — COMMENTED** [review]
Good code, mostly additions without large amounts of code removed, COde shoould work

**Review by hudsonhu22 — CHANGES_REQUESTED** [review]
Should be fine, most changes were systematic the only thing I am worried about is the removal for getUsername from the feed state?

**Comment by hudsonhu22** [comment]
Take a look at the suggested change.

**Pull request merged**
